# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wtmRcpp <- function(x, w) {
    .Call(`_propr_wtmRcpp`, x, w)
}

wtvRcpp <- function(x, w) {
    .Call(`_propr_wtvRcpp`, x, w)
}

corRcpp <- function(X) {
    .Call(`_propr_corRcpp`, X)
}

covRcpp <- function(X, norm_type = 0L) {
    .Call(`_propr_covRcpp`, X, norm_type)
}

vlrRcpp <- function(X) {
    .Call(`_propr_vlrRcpp`, X)
}

clrRcpp <- function(X) {
    .Call(`_propr_clrRcpp`, X)
}

alrRcpp <- function(X, ivar = 0L) {
    .Call(`_propr_alrRcpp`, X, ivar)
}

symRcpp <- function(X) {
    .Call(`_propr_symRcpp`, X)
}

phiRcpp <- function(X, sym = 1L) {
    .Call(`_propr_phiRcpp`, X, sym)
}

rhoRcpp <- function(X, lr, ivar = 0L) {
    .Call(`_propr_rhoRcpp`, X, lr, ivar)
}

indexPairs <- function(X, op = "==", ref = 0) {
    .Call(`_propr_indexPairs`, X, op, ref)
}

indexToCoord <- function(V, N) {
    .Call(`_propr_indexToCoord`, V, N)
}

coordToIndex <- function(row, col, N) {
    .Call(`_propr_coordToIndex`, row, col, N)
}

linRcpp <- function(rho, lr) {
    .Call(`_propr_linRcpp`, rho, lr)
}

lltRcpp <- function(X) {
    .Call(`_propr_lltRcpp`, X)
}

urtRcpp <- function(X) {
    .Call(`_propr_urtRcpp`, X)
}

labRcpp <- function(nfeats) {
    .Call(`_propr_labRcpp`, nfeats)
}

half2mat <- function(X) {
    .Call(`_propr_half2mat`, X)
}

ratiosRcpp <- function(X) {
    .Call(`_propr_ratiosRcpp`, X)
}

ctzRcpp <- function(X) {
    .Call(`_propr_ctzRcpp`, X)
}

count_if <- function(x) {
    .Call(`_propr_count_if`, x)
}

pairmutate <- function(counts, group) {
    .Call(`_propr_pairmutate`, counts, group)
}

lr2vlr <- function(lr) {
    .Call(`_propr_lr2vlr`, lr)
}

lr2phi <- function(lr) {
    .Call(`_propr_lr2phi`, lr)
}

lr2rho <- function(lr) {
    .Call(`_propr_lr2rho`, lr)
}

lr2phs <- function(lr) {
    .Call(`_propr_lr2phs`, lr)
}

lrm <- function(Y, W, weighted = FALSE, a = NA_real_, Yfull = matrix(1, 1), Wfull = matrix(1, 1)) {
    .Call(`_propr_lrm`, Y, W, weighted, a, Yfull, Wfull)
}

lrv <- function(Y, W, weighted = FALSE, a = NA_real_, Yfull = matrix(1, 1), Wfull = matrix(1, 1)) {
    .Call(`_propr_lrv`, Y, W, weighted, a, Yfull, Wfull)
}

omega <- function(X, W) {
    .Call(`_propr_omega`, X, W)
}

