# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

corRcpp <- function(X) {
    .Call('propr_corRcpp', PACKAGE = 'propr', X)
}

covRcpp <- function(X, norm_type = 0L) {
    .Call('propr_covRcpp', PACKAGE = 'propr', X, norm_type)
}

vlrRcpp <- function(X) {
    .Call('propr_vlrRcpp', PACKAGE = 'propr', X)
}

clrRcpp <- function(X) {
    .Call('propr_clrRcpp', PACKAGE = 'propr', X)
}

alrRcpp <- function(X, ivar = 0L) {
    .Call('propr_alrRcpp', PACKAGE = 'propr', X, ivar)
}

symRcpp <- function(X) {
    .Call('propr_symRcpp', PACKAGE = 'propr', X)
}

phiRcpp <- function(X, sym = 1L) {
    .Call('propr_phiRcpp', PACKAGE = 'propr', X, sym)
}

rhoRcpp <- function(X, lr, ivar = 0L) {
    .Call('propr_rhoRcpp', PACKAGE = 'propr', X, lr, ivar)
}

indexPairs <- function(X, op = "==", ref = 0) {
    .Call('propr_indexPairs', PACKAGE = 'propr', X, op, ref)
}

indexToCoord <- function(V, N) {
    .Call('propr_indexToCoord', PACKAGE = 'propr', V, N)
}

coordToIndex <- function(row, col, N) {
    .Call('propr_coordToIndex', PACKAGE = 'propr', row, col, N)
}

linRcpp <- function(rho, lr) {
    .Call('propr_linRcpp', PACKAGE = 'propr', rho, lr)
}

lltRcpp <- function(X) {
    .Call('propr_lltRcpp', PACKAGE = 'propr', X)
}

urtRcpp <- function(X) {
    .Call('propr_urtRcpp', PACKAGE = 'propr', X)
}

labRcpp <- function(nfeats) {
    .Call('propr_labRcpp', PACKAGE = 'propr', nfeats)
}

half2mat <- function(X) {
    .Call('propr_half2mat', PACKAGE = 'propr', X)
}

count_if <- function(x) {
    .Call('propr_count_if', PACKAGE = 'propr', x)
}

pairmutate <- function(counts, group) {
    .Call('propr_pairmutate', PACKAGE = 'propr', counts, group)
}

lr2vlr <- function(lr) {
    .Call('propr_lr2vlr', PACKAGE = 'propr', lr)
}

lr2phi <- function(lr) {
    .Call('propr_lr2phi', PACKAGE = 'propr', lr)
}

lr2rho <- function(lr) {
    .Call('propr_lr2rho', PACKAGE = 'propr', lr)
}

lr2phs <- function(lr) {
    .Call('propr_lr2phs', PACKAGE = 'propr', lr)
}

boxRcpp <- function(X, a) {
    .Call('propr_boxRcpp', PACKAGE = 'propr', X, a)
}

ctzRcpp <- function(X) {
    .Call('propr_ctzRcpp', PACKAGE = 'propr', X)
}

lrmRcpp <- function(X) {
    .Call('propr_lrmRcpp', PACKAGE = 'propr', X)
}

wtmRcpp <- function(x, w) {
    .Call('propr_wtmRcpp', PACKAGE = 'propr', x, w)
}

wtvRcpp <- function(x, w) {
    .Call('propr_wtvRcpp', PACKAGE = 'propr', x, w)
}

lrm <- function(X, W, weighted = FALSE) {
    .Call('propr_lrm', PACKAGE = 'propr', X, W, weighted)
}

lrv <- function(X, W, weighted = FALSE) {
    .Call('propr_lrv', PACKAGE = 'propr', X, W, weighted)
}

lrvMod <- function(X, W) {
    .Call('propr_lrvMod', PACKAGE = 'propr', X, W)
}

