# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

propr::wtmRcpp <- function(x, w) {
    .Call(`_propr_propr::wtmRcpp`, x, w)
}

propr::wtvRcpp <- function(x, w) {
    .Call(`_propr_propr::wtvRcpp`, x, w)
}

propr::corRcpp <- function(X) {
    .Call(`_propr_propr::corRcpp`, X)
}

propr::covRcpp <- function(X, norm_type) {
    .Call(`_propr_propr::covRcpp`, X, norm_type)
}

propr::vlrRcpp <- function(X) {
    .Call(`_propr_propr::vlrRcpp`, X)
}

propr::clrRcpp <- function(X) {
    .Call(`_propr_propr::clrRcpp`, X)
}

propr::alrRcpp <- function(X, ivar) {
    .Call(`_propr_propr::alrRcpp`, X, ivar)
}

propr::symRcpp <- function(X) {
    .Call(`_propr_propr::symRcpp`, X)
}

propr::phiRcpp <- function(X, sym) {
    .Call(`_propr_propr::phiRcpp`, X, sym)
}

propr::rhoRcpp <- function(X, lr, ivar) {
    .Call(`_propr_propr::rhoRcpp`, X, lr, ivar)
}

propr::indexPairs <- function(X, op, ref) {
    .Call(`_propr_propr::indexPairs`, X, op, ref)
}

propr::indexToCoord <- function(V, N) {
    .Call(`_propr_propr::indexToCoord`, V, N)
}

propr::coordToIndex <- function(row, col, N) {
    .Call(`_propr_propr::coordToIndex`, row, col, N)
}

propr::linRcpp <- function(rho, lr) {
    .Call(`_propr_propr::linRcpp`, rho, lr)
}

propr::lltRcpp <- function(X) {
    .Call(`_propr_propr::lltRcpp`, X)
}

propr::urtRcpp <- function(X) {
    .Call(`_propr_propr::urtRcpp`, X)
}

propr::labRcpp <- function(nfeats) {
    .Call(`_propr_propr::labRcpp`, nfeats)
}

propr::half2mat <- function(X) {
    .Call(`_propr_propr::half2mat`, X)
}

propr::vector2mat <- function(X, i, j, nfeats) {
    .Call(`_propr_propr::vector2mat`, X, i, j, nfeats)
}

propr::ratiosRcpp <- function(X) {
    .Call(`_propr_propr::ratiosRcpp`, X)
}

propr::results2matRcpp <- function(results, n, diagonal) {
    .Call(`_propr_propr::results2matRcpp`, results, n, diagonal)
}

propr::count_less_than <- function(x, cutoff) {
    .Call(`_propr_propr::count_less_than`, x, cutoff)
}

propr::count_greater_than <- function(x, cutoff) {
    .Call(`_propr_propr::count_greater_than`, x, cutoff)
}

propr::count_less_equal_than <- function(x, cutoff) {
    .Call(`_propr_propr::count_less_equal_than`, x, cutoff)
}

propr::count_greater_equal_than <- function(x, cutoff) {
    .Call(`_propr_propr::count_greater_equal_than`, x, cutoff)
}

propr::ctzRcpp <- function(X) {
    .Call(`_propr_propr::ctzRcpp`, X)
}

propr::getOR <- function(A, G) {
    .Call(`_propr_propr::getOR`, A, G)
}

propr::getORperm <- function(A, G, perm) {
    .Call(`_propr_propr::getORperm`, A, G, perm)
}

propr::permuteOR <- function(A, G, p) {
    .Call(`_propr_propr::permuteOR`, A, G, p)
}

propr::getFDR <- function(actual, permuted) {
    .Call(`_propr_propr::getFDR`, actual, permuted)
}

propr::getG <- function(Gk) {
    .Call(`_propr_propr::getG`, Gk)
}

propr::graflex <- function(A, Gk, p) {
    .Call(`_propr_propr::graflex`, A, Gk, p)
}

propr::lr2vlr <- function(lr) {
    .Call(`_propr_propr::lr2vlr`, lr)
}

propr::lr2phi <- function(lr) {
    .Call(`_propr_propr::lr2phi`, lr)
}

propr::lr2rho <- function(lr) {
    .Call(`_propr_propr::lr2rho`, lr)
}

propr::lr2phs <- function(lr) {
    .Call(`_propr_propr::lr2phs`, lr)
}

lrm <- function(Y, W, weighted, a, Yfull, Wfull) {
    .Call(`_propr_lrm`, Y, W, weighted, a, Yfull, Wfull)
}

lrv <- function(Y, W, weighted, a, Yfull, Wfull) {
    .Call(`_propr_lrv`, Y, W, weighted, a, Yfull, Wfull)
}

